services:
  hobbyhub:
    image: ${DOCKER_REGISTRY-}hobbyhub
    build:
      context: .
      dockerfile: HobbyHub/Dockerfile
    env_file:
      - HobbyHub/.env
    networks:
      - dev
    depends_on:
     - postgres

  postgres:
    container_name: Postgres
    image: "postgres:17rc1-alpine"
    user: postgres

    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=HobbyHub
    - POSTGRES_PASSWORD=Qwerty_123456

networks:
  dev:
    driver: bridge

volumes:
  db-data:
  